backend = "glx";
vsync = true;
use-damage = true;

shadow = false;
fading = false;
corner-radius = 0;

active-opacity = 1.0;
inactive-opacity = 1.0;

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 1.0; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-off = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 1.0; };
  dropdown_menu = { opacity = 1.0; };
};